name: docs

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
  publish:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Publish to GitHub Pages
        env:
          USE_SSH: false
          GIT_USER: petrbroz
          GIT_PASS: ${{ secrets.GH_PAGES_DEPLOY }}
          ENV: development
        run: |
          git config --global user.email "petr.broz@autodesk.com"
          git config --global user.name "petrbroz"
          if [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run deploy
